version: '2'
services:
  web:
    build: .
    links:
      - db:db
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db-config:/docker-entrypoint-initdb.d
volumes:
  db_data:
