wordpress:
  build: .
  links:
    - db:mysql
  ports:
    - 8080:80
  environment:
    WORDPRESS_DB_PASSWORD: wordpress
  volumes:
    - .:/var/www/html/wp-content/themes/ninteen-thirty-four
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: wordpress
  volumes_from:
    - data
data:
  image: mysql
  entrypoint: /bin/bash
